### ISSUE TITLE
luajit -bl support.

### ISSUE THREAD

**Issue by xpol** [SublimeLinter/SublimeLinter-lua#3]
In case the user have luajit installed rather than lua.

We can use `luajit -bl` instead of `luac -p`.

I have do that for Atom linter-lua [here](https://github.com/AtomLinter/linter-lua/pull/6).
But not sure that SublimeLinter-lua can do it via settings.

**Comment by braver** [comment]
I’m not against the idea, but please create a new linter plugin that uses `luajit`. One plugin should implement one linter executable.
