### ISSUE TITLE
Linter seems broken

### ISSUE THREAD

**Issue by CottonEaster** [SublimeLinter/SublimeLinter-lua#7]
I've installed your linter from within SublimeText 3 - and I have the main linter package installed - but, when a lua script is in the editor, the status bar reads 'lua(erred)' and/but ctrl-K, a produces the message 'no lint results', even when I introduce a mistake deliberately into the script.

Sublime 3175
SublimeLinter 4.5.1
SiblimeLinter-Lua 1.1.0
Linux Mint 18.3

**Comment by kaste** [comment]
Hi! Please enable debug mode in the SublimeLinter settings. Look if the cmd and working dir look reasonable. And then of course look at the generated output from that cmd.

**Comment by CottonEaster** [comment]
Thank you.

[Here](https://pastebin.com/v53gBT3V)'s some relevant - well, I hope it's relevant - output, from before I told Sublime to lint.

When I do tell Sublime to lint a lua script, the output seems to be, only:

> SublimeLinter: sublime_linter.py:286: Linting buffer 47 took 0.01s

**Comment by kaste** [comment]
Okay, it doesn't find 'luac' in the PATH. Ask 'which luac' on the command line. Then probably the easiest way is to set 'executable' to exactly that bin from the which call.

**Comment by CottonEaster** [comment]
Ah; I didn't have, er, lua, installed. I'd managed to overlook this because I run lua scripts via conky, which must have its own special way of running them. I installed lua via my Software Manager (I don't know exactly which package(s) got installed; I did try, first, to find a likely looking package using Synaptic, but there were lots of lua-ish packages and I didn't know which to install).

So: user error, though it would be good were the Linter to give a more informative error message. Thanks for your help.

**Comment by kaste** [comment]
:tada:

Just write down what you would like as a feedback from the linter.

**Comment by CottonEaster** [comment]
I like the party popper!

The error message should reflect the problem. I am not entirely sure what the problem is. But/so perhaps we could have this text:

> Lua linter non-functional: perhaps lua itself is not installed.

though that message might prompt people to ask you which packages exactly are at issue.
